version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.staging
    image: acquisition-api:staging
    restart: unless-stopped
    ports:
      - "${PORT:-3001}:3000"
    env_file:
      - .env.staging
    environment:
      - NODE_ENV=staging
      - PORT=3000
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
