version: '3.8'

services:
  # Production application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: acquisition-app-prod
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    # Remove volumes in production for security and performance
    volumes: []
    # Remove neon-local dependency
    depends_on: []
    networks:
      - acquisition-network
    restart: unless-stopped
    # Production-specific configuration
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  acquisition-network:
    driver: bridge
