version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      NODE_ENV: development
      LOG_LEVEL: info
      PORT: "3000"
      # DATABASE_URL must be provided in .env and should point to a Neon Postgres connection string.
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:3000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
