name: CI - Lint and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint

  test:
    name: Apply DB schema and run tests
    runs-on: ubuntu-latest
    needs: lint
    env:
      NODE_ENV: test
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Check DATABASE_URL present
        run: |
          if [ -z "${DATABASE_URL}" ]; then
            echo "DATABASE_URL is not set" >&2
            exit 1
          fi
          echo "DATABASE_URL is set"
      - name: Apply DB schema (drift-based)
        run: npx drizzle-kit push
      - name: Run Jest tests
        run: npm test -- --forceExit
      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
