name: Release Docker Image

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      DOCKERHUB_REPO: ${{ vars.DOCKERHUB_REPO }}
    steps:
      - uses: actions/checkout@v4

      - name: Determine tags
        id: meta
        run: |
          REF="${GITHUB_REF}"
          SHA="${GITHUB_SHA::7}"
          if [[ "$REF" == refs/tags/v* ]]; then
            TAG="${REF#refs/tags/}"
            echo "tags=${{ env.DOCKERHUB_REPO }}:${TAG},${{ env.DOCKERHUB_REPO }}:latest,${{ env.DOCKERHUB_REPO }}:${SHA}" >> $GITHUB_OUTPUT
            echo "version=${TAG}" >> $GITHUB_OUTPUT
          else
            echo "tags=${{ env.DOCKERHUB_REPO }}:latest,${{ env.DOCKERHUB_REPO }}:${SHA}" >> $GITHUB_OUTPUT
            echo "version=" >> $GITHUB_OUTPUT
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.prod
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ steps.meta.outputs.version }}
